# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins:
  - jekyll-paginate
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://www.lazyfrosch.de
title: Markus Frosch
author: Markus Frosch
description: About Markus Frosch
avatar: mfrosch.png
email: markus@lazyfrosch.de
github: lazyfrosch
twitter: lazyfrosch
#stackoverflow: username   #e.g: users/2735833/proton1h1

# needed for travis-ci build
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
